apiVersion: v1
kind: Pod
metadata:
  name: test-nginx
  labels:
    name: test-nginx
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80
    securityContext:
      capabilities:
        add:
        - cap_net_bind_service
        drop:
        - all
