name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: pwd
      run: pwd
    - name: ls
      run: ls
      
    - name: Install dependencies
      run: make init
      
    - name: Run test
      run: make gotest
